name: GitHub Action Maven Build Example 

on: 
  push:
    branches: [main]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v4

    - name: Step 2 - Set up JDK 19
      uses: actions/setup-java@v1
      with:
        java-version: '19'

    - name: Step 3 - Build Maven Project
      working-directory: CarAccessoriesCompany
      run: mvn --batch-mode -DskipTests package
      
    - name: Step 4 - Run test cases 
      working-directory: CarAccessoriesCompany
      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
      
   
