name: GitHub Action Maven Build Example 

on: 
  push:
    branches: [main]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v4

    - name: Step 2 - Set up JDK 19
      uses: actions/setup-java@v1
      with:
        java-version: '19'

    - name: Step 3 - Build Maven Project
      working-directory: CarAccessoriesCompany
      run: mvn --batch-mode -DskipTests package

    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B -f CarAccessoriesCompany/pom.xml  verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=CE-Riham_Car-accessories-company
